Add controller firmware
robotics-laboratory/whiteboard-bot pull request #2
Opened 2023-02-08 17:34 UTC by enaix

2023-02-26 10:12 UTC, AndBondStyle requested changes

2023-02-26 10:12 UTC, AndBondStyle commented on .gitignore
> +secrets.ini
Обычно такие вещи кладут в стандартный файл `.env`. Для конфига platformio можно [использовать шаблоны](https://docs.platformio.org/en/latest/projectconf/interpolation.html)

2023-02-26 10:12 UTC, AndBondStyle commented on docs/communication.md
> +Note: on the local network it usually appears to be `192.168.1.121`
Надо добавить mdns в прошивку, IP адреса сложно запомнить. Например для бота `wbb-bot.local`, а для распберри `wbb-server.local`

2023-02-26 10:12 UTC, AndBondStyle commented on docs/communication.md
> +`code`: 0 to move forward, 1 to move backward, 2 to stop. The bot continues to move until the stop command is received
Пока не смотрел в коде, но звучит как bad practice. Бот должен останавливаться, если по вебсокету перестали приходить сообщения. Причем делать это практически моментально (т.е. keepalive в районе 100-200ms)

2023-02-26 10:12 UTC, AndBondStyle commented on docs/communication.md
> +`direction`: from 0 to 180, where 0 makes full left rotation, 90 makes forward movement and 180 makes full right rotation
Лучше в радианах, но это надо всем вместе обсудить

2023-02-26 10:12 UTC, AndBondStyle commented on docs/hardware.md
> +Open `hardware/wbb/secrets.ini` and insert WiFi SSID and password
Заменить на .env

2023-02-26 10:12 UTC, AndBondStyle commented on docs/hardware.md
> +`pio run --target upload --upload-port /dev/ttyUSB0` - Build and upload the firmware (may be on another port)
Кажется порт не нужен, platformio его автоматически определяет довольно неплохо

2023-02-26 10:12 UTC, AndBondStyle commented on docs/hardware.md
> +#### In case of permission denied errors, you need to install board udev rules
Не уверен что оно здесь нужно. Достаточно эту ссылочку оставить. По сути ты просто переписал часть внешней доки. https://docs.platformio.org/en/stable/core/installation/udev-rules.html

2023-02-26 10:12 UTC, AndBondStyle commented on docs/hardware.md
> +`cd hardware/wbb`
По поводу структуры проекта, я бы сделал также, как сейчас в cartpole. То есть все команды запускаются строго из корня проекта, `platformio.ini` тоже лежит в корне проекта, а в папке firmware уже непосредственно файлы прошивки (и без префикса src)

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/controller.py
> +        on_release=release_event)
Код стайл питона: линтер black со стандартными настройками + `isort --profile black`

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/controller.py
> +        if str(key) in list(keys_bind):
💀💀💀
```
action = keys_bind.get(str(key))
if action is not None:
    loop.call(..., action)
```

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/controller.py
> +        loop.call_soon_threadsafe(queue.put_nowait, "2")
Все магические константы должны быть в енамах в верхней части файла (так же, как и в прошивке)

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/controller.py
> +    ip = sys.argv[1]
Переделать на argparse

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/controller.py
> +    asyncio.run(main())
По сути тебе нужно синхронный и асинхронный код дружить, это всега немного топорно выглядит. Так что если честно я бы просто взял синхронную либку для веб-сокетов, например https://github.com/websocket-client/websocket-client

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/include/README
> +
Директории include, lib и test можно убить (вместе с readme)

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/platformio.ini
> +extra_configs =
Лучше переделать на .env

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +#define ENB 14 // speed B
Нейминг максимально ничего не объясняющий. Можешь в доках хотя бы указать ссылку на модуль, и написать за что каждый пин отвечает. (да можно даже не в доках, хотя бы в комментах в коде)

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +#define MAX_SPEED_B 255
Тоже странно выглядит. Надо написать коммент, что это такое. И не понятно зачем маппить от 0 до 255, я бы флоты взял от 0.0 до 1.0

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +            go(false, true, false, true);
Вот эту логику переключения я бы всю вынес в отдельный класс L298N. И сделать там один единственный метод `void update(float left, float right)`. Скорость от -1 до 1, 0.0 отключает мотор

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +void event(AsyncWebSocket *server, AsyncWebSocketClient *client, AwsEventType type, void *arg, uint8_t *data, size_t len)
Протокол тоже довольно корявый, его бы вынести в отдельную сущность

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +    if (type == WS_EVT_DATA)
Тут на любителя, но т.к. у тебя аж 3 вложенных ифа, я бы переписал на early return
```
if (type != WS_EVT_DATA) return;
```

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +void smoothMovement()
Пытался понять что тут написано, но так и не получилось. Гораздо проще было бы просто иметь две переменных: target_speed и current_speed (могут принимать и отрицательные, и положительные значения)

2023-02-26 10:12 UTC, AndBondStyle commented on hardware/wbb/src/wbb.cpp
> +    smoothMovement();
Нет никакой проверки на то, сколько времени прошло. Т.е. частота вызова этой функции зависит от тактовой частоты процессора, и от того, насколько долго выполнялись остальные функции в loop

2023-02-27 07:12 UTC, enaix commented on .gitignore
> +secrets.ini
Перенес переменные в .env, в platformio.ini считываю через ${sysenv.<var>}

2023-02-27 08:00 UTC, AndBondStyle commented on .env
> +#!/bin/sh
Не, .env файл это не скрипт. Можешь почитать доки утилит, которые умеют с ним работать, например [docker](https://docs.docker.com/compose/environment-variables/set-environment-variables/), либа для [ноды](https://github.com/motdotla/dotenv), либа для [питона](https://github.com/theskumar/python-dotenv)

2023-02-27 08:02 UTC, AndBondStyle commented on firmware/lib/README
> +
Если тут ничего не будет, то можно убить

2023-03-01 17:09 UTC, enaix commented on .env
> +#!/bin/sh
Поправил, теперь оно парсится через python-dotenv

2023-03-01 17:36 UTC, enaix commented on docs/communication.md
> +`code`: 0 to move forward, 1 to move backward, 2 to stop. The bot continues to move until the stop command is received
Добавил таймаут

2023-03-10 18:07 UTC, dasimagin commented on .gitignore
> +.env
Там все же уже пароли... я б оставил под `cvs`...

2023-03-10 18:08 UTC, dasimagin commented on docs/communication.md
> +Note: on the local network it usually appears to be `192.168.1.121`
+1

2023-03-10 18:35 UTC, dasimagin commented on firmware/src/wbb.cpp
> +#define WS_TIMEOUT_MS 200
Расскажу и вам свое отношение к макросам... их можно использовать в крайнем случае :)

```
constexpr int NAME = 100500;
```

2023-03-10 18:38 UTC, dasimagin commented on firmware/src/wbb.cpp
> +#define ENB 14 // L298N speed for motor B
```
// your
constexpr int ENA = 27; // L298N speed for motor A

// mine
constexpr int L298N_LEFT_MOTOR_SPEED_PIN = 27;
```

2023-03-10 18:39 UTC, dasimagin commented on firmware/src/wbb.cpp
> +#define MOTOR_SPINUP_TIME 1000 // Smoothly increasing/decreasing motor speed for x milliseconds
Не стесняйтесь добавлять единицы измерения `_MS`.

2023-04-07 12:33 UTC, enaix commented on hardware/controller.py
> +    asyncio.run(main())
Сделал все взаимодействия через atomic

2023-04-12 12:16 UTC, AndBondStyle requested changes

2023-04-12 12:16 UTC, AndBondStyle commented on .gitignore
> +
Че-то очень много пустых строчек

2023-04-12 12:16 UTC, AndBondStyle commented on docs/communication.md
> +Note: on the local network it usually appears to be `192.168.1.121`
Уже не актуально? Заменить на mdns

2023-04-12 12:16 UTC, AndBondStyle commented on docs/communication.md
> +`<code>;<direction>;`
Или тут уже весь документ не актуален?

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +constexpr int MOTOR_MAX_SPEED_MMPS = 100; // Max motor speed in millimeter
?

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +constexpr int MOTOR_SPINUP_TIME_MAX_SPEED_MS = 250; // Smoothly increasing/decreasing motor speed for x milliseconds to the top speed
Наверное потом лучше это задать в виде ускорения, но пока сойдет

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +constexpr int ROBOT_BASE_MM = 80;
Очень абстрактное название, и без комментария. Возможно, лучше на что-то типа TRACK_WIDTH или WHEEL_BASE_WIDTH заменить

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +constexpr int VELOCITY_RAD_SEC = 5;  // Velocity (in radians/seconds) for each wheel
Я не понял в чем прикол. Ты скорость контролировать не можешь, это же сервомашинки без обратной связи

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +constexpr int MAX_SPEED_MM_S = 500;  // Max linear speed (in mm/s)
Я бы в прошивке не ограничивал макс. скорость, но пока можно оставить. + мы обычно используем метры, радианы и секунды

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +        MDNS.addService(SERVICE_NAME, SERVICE_PROTOCOL, SERVICE_PORT);
Если честно, это лишнее. Нам достаточно того, чтобы по фиксированному hostname.local можно было заходить. Сервисами я вообще не знаю кто пользуется

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +enum Direction
Уже не нужно?

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +static std::atomic<Direction> dir(STOP);
Тоже

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +    target_speed_right.store(0);
Тут надо сразу останавливаться, а не просто переменные обновлять

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +constexpr float min_diff_coeff = 0.0001;
Diff coef это кривизна? Если да, используй лучше название curvature, иначе приходится догадываться

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +    int radius = int(1/coeff);
Это кажется бан

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +}
Это очень странно и запутанно выглядит.
1. Почему радиус передается в виде int?
2. Зачем ты используешь is_left, если скорость можно вычислить для каждой гусеницы независимо?
3. Что за гениальная функция calcSpeed? Которая просто возвращает результат другой функции
4. Не разобраны случаи, когда радиус меньше w/2

![image](https://user-images.githubusercontent.com/18560701/231453004-70653dd1-4239-4385-b810-b95f56940a49.png)

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +        dir.store(cur_dir);
То же самое, логика кривая, и не понятно зачем вообще тебе нужно хранить "направление". Ты не можешь просто хранить скорость каждой гусеницы со знаком, а при обновлении пинов сделать 2 ифа?

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +            break;
Жесть

2023-04-12 12:16 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +    delay(max(1, spinup_delay - int(millis() - loop_time)));
Так конечно не делают, но пусть пока останется

2023-04-12 12:16 UTC, AndBondStyle commented on scripts/fetch_env.py
> +import os
Не понял зачем этот плагин нужен. Если просто указывать переменные в окружении они разве не подхватываются?

2023-04-12 12:56 UTC, dasimagin commented on firmware/src/wbb.cpp
> +constexpr int MOTOR_MAX_SPEED_MMPS = 100; // Max motor speed in millimeter
Как я понял наброс на то, что переменная не используется. Единицы измерения тоже странные. Мы, как четкие пацаны, по умолчанию же в "СИ" работаетм, Метры, Секунды, Килограммы?

**UPD** в связи с текущим устройством мы не можем мыслить в терминах метров.

2023-04-12 12:58 UTC, dasimagin commented on firmware/src/wbb.cpp
> +constexpr int ROBOT_BASE_MM = 80;
За миллиметры тоже бан.

2023-04-12 13:05 UTC, enaix commented on docs/communication.md
> +`<code>;<direction>;`
Не актуален) Хотел сначала убедиться, что текущий протокол устраивает

2023-04-12 13:06 UTC, dasimagin commented on firmware/src/wbb.cpp
> +constexpr int MAX_SPEED_MM_S = 500;  // Max linear speed (in mm/s)
После обсуждения в тредике телеги я вообще понял, что в качестве скорости можно просто число от 0 до 1 посылать в терминах "нажимаю педаль газа".

2023-04-12 13:09 UTC, enaix commented on firmware/src/wbb.cpp
> +constexpr int MOTOR_MAX_SPEED_MMPS = 100; // Max motor speed in millimeter
Удалил, переменная уже не нужна

2023-04-12 13:51 UTC, dasimagin commented on firmware/src/wbb.cpp
> +int smoothMovement(int speed, int target)
Мне в целом нравится почти везде работать в прошивке в терминах `pwm`.

2023-04-12 14:04 UTC, dasimagin commented on firmware/src/wbb.cpp
> +    speed_right = 0;
Точно нужен такой тест?

2023-04-12 14:38 UTC, dasimagin commented on firmware/src/wbb.cpp
> +int speed_right = 0;
Давайте просто заведем 4 глобальных переменные
```
std::atomic<T> command_left_motor_velocity;
std::atomic<T> command_right_motor_velocity;

std::atomic<T> target_left_motor_velocity;
std::atomic<T> target_right_motor_velocity;
```

Я готов предоставить Андрею выбор T это знаковый `int` или `float`. Далее надо научиться аккуратно инкрементить этот значение, проходить 0 и превращать это в конечную команду мотора. А от dir-в конечно же надо избавиться.

2023-04-12 14:40 UTC, dasimagin commented on firmware/src/wbb.cpp
> +int speed_right = 0;
Да, ну и магистральная мысль, что от каких-то ускорений можно отказаться вообще, давайте просто регулировать ускорение икрементом и частотой работы контроллера.

2023-04-12 14:40 UTC, dasimagin commented on firmware/src/wbb.cpp
> +constexpr float min_diff_coeff = 0.0001;
при нормальном использовании кризвины скорее всего будет не нужно

2023-04-12 14:42 UTC, dasimagin commented on firmware/src/wbb.cpp
> +}
+1 там все вычисляется двумя строчками, сейчас что-то ооооочень сложно получилось.

2023-04-12 14:42 UTC, dasimagin commented on firmware/src/wbb.cpp
> +    delay(max(1, spinup_delay - int(millis() - loop_time)));
хех

2023-04-12 14:44 UTC, dasimagin commented on firmware/src/wbb.cpp
> +}
Вот тут можно просто брать command_velocity и превращать в команду в терминах pwm.

2023-04-12 14:46 UTC, dasimagin commented on firmware/src/wbb.cpp
> +    if (info->final && info->index == 0 && info->len == len)
в таких случаях удобне делать ранний выход, что уменьшать вложенность кода.

```
void event(...) {
  if (...) {
    return;
  }

  // your code
  return;
}
```

2023-04-12 14:49 UTC, dasimagin commented on firmware/src/wbb.cpp
> +        if (tok == NULL)
Вроде, уже изобрели `nullptr` или этот макрос до сих пор популярен?

2023-04-12 15:33 UTC, dasimagin commented on firmware/src/wbb.cpp
> +    target_speed_right.store(0);
от частоты контроллера в целом зависит, но лучше и правда сразу.

2023-04-12 15:37 UTC, dasimagin commented on docs/communication.md
> +`<code>;<direction>;`
Я вот коды не понял тоже... мы хотим текст передавать или байты, кстати? Там просто с плавающей точкой надо бы аккуратнее. Лучше использовать fixed пожалуй при сериализации.

2023-04-12 15:38 UTC, dasimagin commented on scripts/controller.py
> +    asyncio.run(main(args))
Этот весь код мы следующим шаго уже в ноду превратим?

2023-04-12 15:39 UTC, dasimagin commented on scripts/fetch_env.py
> +import os
видимо, какой-то дефолт в файле хотелось указать....

2023-05-16 09:40 UTC, enaix commented on firmware/src/wbb.cpp
> +    target_speed_right.store(0);
Тут нельзя резко останавливаться, поскольку тогда бот может свалиться (либо я не так понял)

2023-05-16 10:01 UTC, enaix commented on firmware/src/wbb.cpp
> +    speed_right = 0;
Да, нужно чтобы пропищало что всё работает нормально :)

2023-05-30 01:05 UTC, AndBondStyle requested changes
Краткие итоги:
- В мейне все равно довольно много мусора, нужно перенести всю логику управления моторами в... класс "мотор" (это то что у тебя сейчас называется l298n_driver)
- `.env` выпиливаем, fetch_env.py выпиливаем, поправляем platformio.ini, чтобы он сам брал переменные из окружения
- Протокол не очень нравится, а главное заставляет писать много тупого кода со строковыми манипуляциями (особенно странно выглядит то, что размер сообщения отличается в разных случаях). Я предлагаю либо на бинарный перейти, либо хотя бы код упростить, через scanf например, либо через стримы плюсовые
- Доки привести в порядок (в последнюю очередь)

2023-05-30 01:05 UTC, AndBondStyle commented on .env
> +WIFI_PASSWD="passwd"
Лично я такое не очень люблю, потому что когда файл лежит в репозитории, его кто-нибудь обязательно поменяет, обойдет .gitignore и запушит. Лучше либо вообще не хранить (вынести в доки просто, сделав дополнительный шаг "добавьте .env файл с вот таким-то содержимым"), либо хотя бы назвать в духе `.env.example`

2023-05-30 01:05 UTC, AndBondStyle commented on docs/communication.md
> +Note: on the local network it usually appears to be `192.168.1.121`
Надо поправить

2023-05-30 01:05 UTC, AndBondStyle commented on docs/communication.md
> +`2;`: move eraser down
Посмотрел на структурку... Понятно, что это вообще текстовый протокол, но мне кажется лучше было бы иметь один тип сообщения на все ситуации, т.е. всегда 3 поля: cmd, curvature, velocity. Если cmd != 0, то остальные поля просто игнорируешь (в целом это нормальная стратегия, и многие реальные протоколы именно так и написаны)

2023-05-30 01:05 UTC, AndBondStyle commented on docs/communication.md
> +`2;`: move eraser down
Еще в качестве упражнения можно попробовать в бинаре посылать сообщения (но это уже из разряда баловства). Тогда на стороне плюсов у тебя просто будет стракт а-ля { uint8, float, float }, а на стороне питона распаковка (и запаковка) через либу [struct](https://docs.python.org/3/library/struct.html), типо `struct.unpack("Bff", buffer)`. И не надо будет со строковыми операциями возиться

2023-05-30 01:05 UTC, AndBondStyle commented on docs/hardware.md
> +A quick fix would be to `sudo chown $USER /dev/ttyUSB0`, but you would need to execute it each time you connect the board.
А го сделаем единый readme в корне репозитория, и все туда перенесем в отдельные разделы. А то все документы на пять строчек занимают, кажется лучше объединить это все

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/l298n_driver.cpp
> +void L298N_DRIVER::update(int velocity_left, int velocity_right)
Если придираться, то все стараются строгие типы данных использовать (то есть `int8` в твоем случае), а то мало ли захочешь на другой МК это перенести когда нибудь

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/l298n_driver.cpp
> +void L298N_DRIVER::writeOnce(bool fwd1, bool fwd2, bool fwd3, bool fwd4)
А еще форматирование не везде правильное, можешь pre-commit настроить с любым стандартным стилем типа google, тогда о форматировании не надо будет помнить

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/l298n_driver.h
> +    bool state[4];
Имхо лучше иметь нормальные (и читаемые) переменные, потенциально меньше возможностей что-то глупое сделать

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/l298n_driver.h
> +    int _IN1;
По фен шую должен быть суффикс `_pin` у таких переменных (и в конструкторе тоже). И если уж делаешь их похожими на константы (имею в виду верхний регистр), то можешь const добавить. На мой взгляд `const uint8_t _in2_pin` лучше всего

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/l298n_driver.h
> +#ifndef WHITEBOARD_BOT_L298N_DRIVER_H
Называется `#pragma once`, на дворе 2023 год все-таки)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/l298n_driver.h
> +#endif  // WHITEBOARD_BOT_L298N_DRIVER_H
Еще я не увидел поддержку PWM внутри этого класса, почему она в мейне?

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +constexpr char* SERVICE_NAME = "ws-control";
Все что к "service" относится, тебе не нужно, главное чтобы dns был и все

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    pinMode(L298N_RIGHT_MOTOR_SPEED_PIN, OUTPUT);
Это должно быть в конструкторе L298N

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    spinMotors();
В функцию (а лучше в класс мотора)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +        MDNS.addService(SERVICE_NAME, SERVICE_PROTOCOL, SERVICE_PORT);
Не нужно

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +        delay(1000);
Для приличия лучше что-то в serial port писать. Либо как вариант, делать проверку моторов только после подключения к wifi

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    ws_timeout = timerBegin(0, 80, true);
Выглядит как магическая константа, надо написать откуда число 80 берется. А вообще можно и поменьше поставить прескейлер

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    spinMotors();
Опять же, в плане декомпозиции было бы гораздо лучше вынести ВСЮ логику управления моторами в отдельный класс, и в loop вызывать просто что-то вида `driver.poll()` (а еще лучше вообще без поллинга обойтись, используя таймеры и rtos)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    spinMotors();
Можешь в качестве примера посмотреть на любую библиотеку, которая умеет шаговыми двигателями управлять с заданным ускорением и максимальной скоростью. Там ты создаешь объект, передаешь ему пины, ускорение и скорость, а дальше можно просто делать .set_velocity или .set_position (ну и poll вызывать в лупе)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    ws.cleanupClients();
Есть гарантии за сколько эта функция выполняется? Может ли выполняться дольше, чем эпсилон относительно spinup_delay? Если да, то ее надо поместить до delay (иначе не гарантируется регулярное обновление мотора)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +        Serial.println("Could not initialize MDNS");
Chaotic evil форматирование кода :skull:

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +void spinOnce(bool fwd1, bool fwd2, bool fwd3, bool fwd4)
Блин, это функция только ради того чтобы моторы проверить? Это надо вычистить все из мейна, засунуть в класс с мотором. Иначе невозможно на логике сосредоточиться

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    return map(speed, 0, 255, 0, max);
Это не выглядит как что-то полезное)
Да и все равно это в мотор надо убирать (приватный метод глаза не режет, в отличие от миллиона дурацких функций в мейне)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +        Serial.println("Wrong command");
Можно поймать в свитче. Я бы сказал даже нужно, потому что сейчас ты надеешься на то, что в свитче будут перечислены все значения из енама (а ты всегда можешь забыть)

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    tok = strtok(NULL, ";");
На фронтенде есть понятие "добавить воздуха" (то есть паддинга между элементами). Вот это про стиль этой функции))

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +    tok = strtok(NULL, ";");
Еще вместо того чтобы копипастить "Wrong message format", можно возвращать из функции bool наверх (ок/не ок). Станет немного опрятнее

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +int bound(int velocity)
Называется clamp, есть из коробки. В ардуино вроде constrain называется

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +static std::atomic<int> eraser_servo_angle(ERASER_SERVO_ENGAGED_ANGLE);
Это вкусовщина, но как по мне лучше разделять все что в корне лежит по блокам: константы, переменные состояния, глобальные объекты. Сейчас ты сгруппировал по функционалу, но так сложнее по коду ориентироваться

2023-05-30 01:05 UTC, AndBondStyle commented on scripts/fetch_env.py
> +env.Append(BUILD_FLAGS=flags)
Все это не нужно. Я считаю, что плюс минус любой разработчик умеет обращаться с переменными окружения (есть и консольные утилиты для этого, и плагины для IDE которые автоматически .env читают, и еще миллион других вариантов). А в platformio можно просто это добавить:
```
build_flags = 
    -D WIFI_SSID='"${sysenv.WIFI_SSID}"'
    -D WIFI_PASSWORD='"${sysenv.WIFI_PASSWORD}"'
```

2023-05-30 01:05 UTC, AndBondStyle commented on platformio.ini
> +    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
А этот фреймворк не по умолчанию используется? Просто интересно

2023-05-30 01:05 UTC, AndBondStyle commented on firmware/src/main.cpp
> +const char* password = WIFI_PASSWD;
Достаточно ли мы эволюционировали, чтобы использовать тип string?

2023-05-30 01:05 UTC, AndBondStyle commented on docs/communication.md
> +`2;`: move eraser down
Еще немного подумал. Если все правильно сделать, то флоты конечно будут работать, но на стороне МК будет довольно сложно защититься от того, что тебе пришлют кривой float. Так что везде инты использовать, а внутри кода (если надо) переводить во флоты.

2023-05-30 01:05 UTC, AndBondStyle commented on scripts/controller.py
> +    asyncio.run(main(args))
Вопрос остался. ROS нода уже есть, которая реализует протокол? Если да, то это можно выпилить

2023-05-30 01:06 UTC, AndBondStyle commented on firmware/src/wbb.cpp
> +        if (tok == NULL)
+ 1

2023-08-02 15:17 UTC, closed without merging